default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: syedghani_api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: syedghani_api_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
